title: Faithful Treasury
email: your_email@example.com
description: >-
  Exploring Gods Word, growing in grace, and equipping believers for ministry.
baseurl: "" # Leave as is if you're not using a subfolder for the site
url: "https://faithtreasure.netlify.app/" # Your live site URL (replace this with your URL once deployed)
theme: minima
markdown: kramdown
paginate: 5

# Collections
collections:
  categories:
    output: true
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
 - jekyll-paginate
# Exclude these files from the site output
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include these files in the site output
include:
  - _pages

# Markdown configuration
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Permalinks
permalink: pretty

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"